spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: microservice-config-dept-client-dev

---
spring:
  profiles: test
  application:
    name: microservice-config-dept-client-test